name: ROS 1 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ROS 1 Noetic
        run: |
          sudo apt update
          sudo apt install -y wget gnupg lsb-release
          
          # Download and add the ROS 1 GPG key
          wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
          sudo apt-key add ros.asc
          rm ros.asc
          
          # Add the ROS repository to the sources list
          echo "deb [arch=amd64] http://packages.ros.org/ros/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/ros-latest.list
          
          # Install ROS Noetic
          sudo apt update
          sudo apt install -y ros-noetic-desktop-full

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-catkin-tools python3-pip
          python3 -m pip install -U setuptools

      - name: Source ROS 1 setup script and build
        run: |
          source /opt/ros/noetic/setup.bash
          mkdir -p ~/catkin_ws/src
          cp -r . ~/catkin_ws/src
          cd ~/catkin_ws
          catkin_make
